title: Nexus Mods
description: >
  A collection of extensions and mods for Nexus Mods.

show_exerpts: false

site_favicon: favicon.ico

color_scheme: dark

remote_theme: just-the-docs/just-the-docs

header_pages:
  - index.md
  - README.md